title: HTB-Writeups
description: "My Writeups for HackTheBox"
author:
  name: "iampachinko"
  email: "pachinko28@protonmail.com"
  url: "https://www.hackthebox.eu/profile/105108"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "iampachinko"
year : "2020"
